version: "3.9"

services:

  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS:-toor}"
    # uncomment the following to allow accessing the MongoDB instance publically
    # ports:
    #   - 27017:27017

  app:
    image: ivanpartida/carteleracultural-api:latest
    ports:
      - 3000:3000
    volumes:
      - ccultural-api:/home/node/app/public
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017"
      MONGO_DB: "${MONGO_DB:-ccultural-dev}"
      MAIL_HOST: "${MAIL_HOST:-mail}"
      MAIL_PORT: "${MAIL_PORT:-25}"
      MAIL_USER: "${MAIL_USER:-user}"
      MAIL_PASS: "${MAIL_PASS:-pass}"
      MAIL_SECURE: "${MAIL_SECURE:-false}"
      MAIL_SENDER_ADDRESS: "${MAIL_SENDER_ADDRESS:-no-reply@example.com}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET:-someStrongSecret}"
      REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET:-someOtherStrongSecret}"
      JWT_ISSUER: "${JWT_ISSUER:-some-domain.com}"
      JWT_AUDIENCE: "${JWT_AUDIENCE:-some-other-domain.com}"
volumes:
  ccultural-api:
