name: CD
on:
  push:
    branches: ["main"]
jobs:
  build:
    uses: ./.github/workflows/ci.yml
    secrets:
      TEST_MAIL_HOST: ${{ secrets.TEST_MAIL_HOST }}
      TEST_MAIL_PORT: ${{ secrets.TEST_MAIL_PORT }}
      TEST_MAIL_USER: ${{ secrets.TEST_MAIL_USER }}
      TEST_MAIL_PASS: ${{ secrets.TEST_MAIL_PASS }}
      TEST_MAIL_ADDRESS: ${{ secrets.TEST_MAIL_ADDRESS }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ivanpartida/carteleracultural-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: SSH remote action
        uses: appleboy/ssh-action@v0.1.5
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: cd carteleracultural-api/ && make build
